---
title: "Predicting Credit Default"
author: "Ronan Morris"
date: "2023-06-26"
output:
  pdf_document: 
    latex_engine: xelatex
header-includes:
  - \usepackage{ragged2e}
  - \usepackage{titlesec}
  - \titleformat*{\section}{\fontsize{12}{14}\bfseries}
  - \titleformat*{\subsection}{\fontsize{12}{14}\itshape}
   -0 \setlength{\spaceskip}{1.5\fontdimen2\font}
  - \usepackage{fontspec}
  - \setmainfont{Times New Roman}
  - \justifying
editor_options: 
  chunk_output_type: console
---

```{r Setup, include = FALSE}

#tinytex::install_tinytex(force = TRUE)
#options(repos = "https://cran.mirror.ac.za/")

#Installing Packages 

#install.packages("caret")
#install.packages("tidyverse")
#install.packages("ggplot2")
#install.packages("randomForest")
#install.packages("glmnet")

```

```{r Data Design, include = FALSE}

rm(list = ls())

# The full set

Data <- read.csv("Data/Credit Default Dataset.csv")
Data <- na.omit(Data)
Data <- subset(Data, Amount != 0)
Data <- subset(Data, Age >= 22 & Age < 65)

# Specific Columns

Data$Gender <- gsub("2", "0", Data$Gender) # 0 == Female 

Data$Education <- gsub("4|5|6", "0", Data$Education) 
    Data$Education <- gsub("2|1", "2", Data$Education) # Uni+ = 2, HS = 1
    Data$Education <- gsub("3", "1", Data$Education)

Data$Marriage.Status <- gsub("2|3", "0", Data$Marriage.Status)# Married = 1

Data$Quality <- ((Data[, 6] + 
                Data[, 7] + 
                Data[, 8] +
                Data[, 9] +
                Data[, 10] +
                Data[, 11]))/6 # pay before, on time, or late. (average)

Data$Quality <- ifelse(Data$Quality < -1, 2,
                ifelse(Data$Quality < 0 & Data$Quality >= -1, 1,
                ifelse(Data$Quality > 0 & Data$Quality < 2, -1, 
                ifelse(Data$Quality >= 2, -2,0))))

Data$Owed <- rowSums(Data[,c(12,13,14,15,16,17)])
Data <- subset(Data, Owed != 0)

Data$TotalPaid <- rowSums(Data[,c(18,19,20,21,22,23)])

Data$Difference <- (Data$Owed - Data$TotalPaid)

Data <- subset(Data, Owed != 0)
Data <- subset(Data, Amount != 0)
Data <- subset(Data, Age >= 22 & Age < 65)

# Interactions

Data <- as.data.frame(lapply(Data, as.numeric))

Data$IntAgeMarr <- Data$Age*Data$Marriage.Status
Data$IntEducAmt <- Data$Education*Data$Amount
Data$IntEducQua <- Data$Education*Data$Quality
Data$IntAgeAmt <- Data$Age*Data$Amount
Data$GenAmt <- Data$Gender*Data$Amount

Standardised <- c(1, 28, 5, 29)

Process <- function(a, b) {
  b[, a] <- scale(b[, a])
  NewData <<- b
} # might want to do again later.

Process(Standardised, Data) # Standardised Data
rm(Standardised)

#Monetary sums have either been logged (amount loaned) or standardised.

```

```{r Feautre Selection, include=FALSE}

library(glmnet)
library(caret)

set.seed(123)  
Training <- createDataPartition(NewData$Default..Outcome., p = 0.8, list = FALSE)
Train <- NewData[Training, ]
Test <- NewData[-Training, ]

X <- as.matrix(Train[, -24])
Y <- Train$Default..Outcome.

#  elastic net model
ElasticNet <- glmnet(X, Y, family = "binomial", alpha = 0.5)

# cross-validation
CV <- cv.glmnet(X, Y, family = "binomial", alpha = 0.5)
TrueL <- CV$lambda.min

ElasticFinal <- glmnet(X, Y, family = "binomial", alpha = 0.5, lambda = TrueL)

# Final Features

Features <- rownames(coef(ElasticFinal))[coef(ElasticFinal)[, 1] != 0]

print(Features)

Pred2 <- predict(ElasticFinal, newx = as.matrix(Test[, -which(names(Test) == "Default..Outcome.")]), type = "response")
Pred2 <- ifelse(Pred2 >= 0.5, 1, 0)

Success <- sum(Pred2[Test$Default..Outcome. == 1] == 1) / sum(Test$Default..Outcome. == 1)

Fail <- sum(Pred2[Test$Default..Outcome. == 0] == 0) / sum(Test$Default..Outcome. == 0)

print(c(Success, Fail))

```

```{r ML Model, include=FALSE}

library(randomForest)

MLModel <- randomForest(
  Default..Outcome. ~ ., 
  data = Train, 
  ntree = 100,
  mtry = 5,
  nodesize = 50, 
  maxdepth = 50)

###

Predict <- predict(MLModel, newdata = Test)
Predict <- ifelse(Predict >= 0.5, 1, 0)

Success <- sum(Predict[Test$Default..Outcome. == 1] == 1) / sum(Test$Default..Outcome. == 1)

Fail <- sum(Predict[Test$Default..Outcome. == 0] == 0) / sum(Test$Default..Outcome. == 0)

print(c(Success, Fail))

# End the day off at 38%.  

```

